/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joinme.GUI;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import joinme.controlador.ControladorListaAmigos;
import joinme.modelo.usuario.Usuario;

/**
 *
 * @author esteban
 */
public class ListaAmigos extends javax.swing.JFrame {
    private static Usuario usuario;
    private static Usuario usuarioConsultado;
    private final ControladorListaAmigos controlador;
    
    private static void setUsuario (Usuario usuario){
        ListaAmigos.usuario = usuario;
    }
    
    /**
     * Creates new form ListaAmigos
     */
    public ListaAmigos(Usuario usuario, Usuario usuarioConsultado) {
        controlador = new ControladorListaAmigos();
        setUsuario(usuario);
        this.usuarioConsultado = usuarioConsultado;
        initComponents();
        init();
    }
    
    public void init(){
        jLabel1.setText("Amigos de "+usuarioConsultado.getAlias());
        List <Usuario> amigos = controlador.getAmigos(usuarioConsultado);
        
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        if (amigos != null){
            for(Usuario u : amigos) {
                modelo.addElement(controlador.getAlias(u));
            }
        }
        jListAmigos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListAmigos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jVolverPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListAmigos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Victor", "Jelen", "Mateo", "Esteban", "Jose", "Pillado" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verAmigos(evt);
            }
        });
        jScrollPane1.setViewportView(jListAmigos);

        jLabel1.setText("Lista de Amigos");

        jVolverPerfil.setText("Volver al Perfil");
        jVolverPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jVolverPerfil)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jVolverPerfil)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verAmigos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verAmigos
        String valor = (String) jListAmigos.getSelectedValue();
        controlador.verAmigos(usuario, valor, this);
    }//GEN-LAST:event_verAmigos

    private void jVolverPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverPerfilActionPerformed
        controlador.getPerfil(usuario, usuarioConsultado, this);
    }//GEN-LAST:event_jVolverPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAmigos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAmigos(usuario,usuarioConsultado).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListAmigos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jVolverPerfil;
    // End of variables declaration//GEN-END:variables
}
