/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joinme.GUI;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import joinme.controlador.ControladorPaginaPrincipal;
import joinme.modelo.usuario.Usuario;

/**
 *
 * @author esteban
 */
public class PagPrincipal extends javax.swing.JFrame {
    private static Usuario usuario;
    private ControladorPaginaPrincipal controlador;
    
    /**
     * Creates new form Perfil
     */
    public PagPrincipal(Usuario usuario) {
        controlador = new ControladorPaginaPrincipal();
        this.usuario = usuario;
        initComponents();
        init();
    }

    
    private void init() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        DefaultComboBoxModel modelo2 = new DefaultComboBoxModel();

        //Datos del usuario
        String alias = controlador.getAlias(usuario);
        jBotonPerfil.setText("Perfil de "+ alias);
        jLabelNombre.setText(controlador.getNombre(usuario));
        jLabelAp1.setText(controlador.getApellido1(usuario));
        jLabelAp2.setText(controlador.getApellido2(usuario));
        jLabelAlias.setText(alias);
        jLabelCumple.setText(controlador.getFechaNac(usuario));
        

        //Peticiones pendientes
        jPeticionesPendientes.setText("Peticiones pendientes");
        boolean pendientes = false;
        pendientes = controlador.getSolicitudesPendientes(usuario);
        jPeticionesPendientes.setEnabled(pendientes);
        
        //Entradas en el muro
        List<String> lista=null;
        lista = controlador.getEventos(usuario, controlador.getAmigos(usuario));
        for (int i=0;i<lista.size();i++)
            modelo.addElement(lista.get(i));
        jListEventos.setModel(modelo);
        
        //Lista de no amigos
        List<String> listaNoAmigos=null;
        listaNoAmigos = controlador.getListaNoAmigos(usuario);
        for (int i=0;i<listaNoAmigos.size();i++)
            modelo2.addElement(listaNoAmigos.get(i));
        jListNoAmigos.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAp1 = new javax.swing.JLabel();
        jLabelAlias = new javax.swing.JLabel();
        jLabelCumple = new javax.swing.JLabel();
        jBotonDesconectar = new javax.swing.JButton();
        jLabelAp2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBotonVerAmigos = new javax.swing.JButton();
        jBotonPublicar = new javax.swing.JButton();
        jBotonPerfil = new javax.swing.JButton();
        jPeticionesPendientes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEventos = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListNoAmigos = new javax.swing.JList();
        jVerPerfil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagina Principal");
        setAlwaysOnTop(true);

        jLabel1.setText("jLabelFoto");

        jLabelNombre.setText("jLabelNombre");

        jLabelAp1.setText("jLabelApellido");

        jLabelAlias.setText("jLabelAlias");

        jLabelCumple.setText("jLabelCumple");

        jBotonDesconectar.setText("Desconectar");
        jBotonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDesconectarActionPerformed(evt);
            }
        });

        jLabelAp2.setText("jLabelAp2");
        jLabelAp2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAp1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAp2))
                            .addComponent(jLabelAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                        .addComponent(jBotonDesconectar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelCumple, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBotonDesconectar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelAp1)
                    .addComponent(jLabelAp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAlias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabelCumple)
                .addContainerGap())
        );

        jBotonVerAmigos.setText("Lista de amigos");
        jBotonVerAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVerAmigosActionPerformed(evt);
            }
        });

        jBotonPublicar.setText("Publicar");
        jBotonPublicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPublicarActionPerformed(evt);
            }
        });

        jBotonPerfil.setText("Perfil");
        jBotonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonPerfilActionPerformed(evt);
            }
        });

        jPeticionesPendientes.setText("PeticionesPendientes");
        jPeticionesPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPeticionesPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPeticionesPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonVerAmigos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBotonPerfil, jBotonPublicar, jBotonVerAmigos});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBotonVerAmigos)
                .addComponent(jBotonPublicar)
                .addComponent(jBotonPerfil)
                .addComponent(jPeticionesPendientes))
        );

        jListEventos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListEventos);

        jScrollPane2.setViewportView(jScrollPane1);

        jListNoAmigos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListNoAmigos);

        jVerPerfil.setText("Ver Perfil");
        jVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerPerfilActionPerformed(evt);
            }
        });

        jLabel2.setText("Lista de no amigos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jVerPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVerPerfil))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPerfilActionPerformed
        controlador.getMiPerfil(usuario, this);
    }//GEN-LAST:event_jBotonPerfilActionPerformed

    private void jBotonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDesconectarActionPerformed
       controlador.desconectar(this);
        
    }//GEN-LAST:event_jBotonDesconectarActionPerformed

    private void jBotonVerAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVerAmigosActionPerformed
        controlador.verAmigosActionPerformed(usuario,this);
    }//GEN-LAST:event_jBotonVerAmigosActionPerformed

    private void jVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerPerfilActionPerformed
         if(!jListNoAmigos.isSelectionEmpty()){
            String alias = (String) jListNoAmigos.getSelectedValue();
            controlador.getPerfil(alias, usuario, this);
        }
    }//GEN-LAST:event_jVerPerfilActionPerformed

    private void jPeticionesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPeticionesPendientesActionPerformed
        controlador.getSolicitudes(usuario, this);
    }//GEN-LAST:event_jPeticionesPendientesActionPerformed

    private void jBotonPublicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonPublicarActionPerformed
        controlador.publicarEntrada(usuario, this);
    }//GEN-LAST:event_jBotonPublicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagPrincipal(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonDesconectar;
    private javax.swing.JButton jBotonPerfil;
    private javax.swing.JButton jBotonPublicar;
    private javax.swing.JButton jBotonVerAmigos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAlias;
    private javax.swing.JLabel jLabelAp1;
    private javax.swing.JLabel jLabelAp2;
    private javax.swing.JLabel jLabelCumple;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JList jListEventos;
    private javax.swing.JList jListNoAmigos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jPeticionesPendientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jVerPerfil;
    // End of variables declaration//GEN-END:variables
}
