/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joinme.GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import joinme.controlador.ControladorSolicitudAmistad;
import joinme.modelo.usuario.GestorUsuario;
import joinme.modelo.usuario.Solicitud;
import joinme.modelo.usuario.Usuario;

/**
 *
 * @author jose
 */
public class SolicitudAmistad extends javax.swing.JFrame {
    private static Usuario usuario;
    private ControladorSolicitudAmistad controlador;

    /**
     * Creates new form SolicitudAmistad
     */
    public SolicitudAmistad(Usuario usuario) {
        this.usuario = usuario;
        controlador = new ControladorSolicitudAmistad();
        initComponents();
        init();
    }

    // Deberíais cargar sólo las solicitudes con estado = Pendiente ;)
    private void init() {
        boolean haySolicitudes = false;
        jLabelSolicitudes.setText("Solicitudes a " + controlador.getAlias(usuario));

        DefaultComboBoxModel modelo1 = new DefaultComboBoxModel();
        //Solicitudes
        List<String> listaSolicitudes = new ArrayList();
        listaSolicitudes = controlador.getSolicitudes(usuario);
        for (int i=0;i<listaSolicitudes.size();i++) {
            modelo1.addElement(listaSolicitudes.get(i));
            haySolicitudes = true;
        }
        if (haySolicitudes == false) {
            jAceptarAmistad.setEnabled(false);
            jRechazarAmistad.setEnabled(false);      
        }
        jListaSolicitudes.setModel(modelo1);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSolicitudes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaSolicitudes = new javax.swing.JList();
        jBotonVolver = new javax.swing.JButton();
        jRechazarAmistad = new javax.swing.JButton();
        jAceptarAmistad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSolicitudes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSolicitudes.setText("jLabel1");

        jListaSolicitudes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListaSolicitudes);

        jBotonVolver.setText("Volver");
        jBotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonVolverActionPerformed(evt);
            }
        });

        jRechazarAmistad.setText("Rechazar");
        jRechazarAmistad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRechazarAmistadActionPerformed(evt);
            }
        });

        jAceptarAmistad.setText("Aceptar");
        jAceptarAmistad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAceptarAmistadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBotonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jRechazarAmistad)
                .addGap(96, 96, 96)
                .addComponent(jAceptarAmistad))
            .addComponent(jScrollPane1)
            .addComponent(jLabelSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAceptarAmistad, jBotonVolver, jRechazarAmistad});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAceptarAmistad)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotonVolver)
                        .addComponent(jRechazarAmistad))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonVolverActionPerformed
        controlador.pagPrincipal(usuario, this);
    }//GEN-LAST:event_jBotonVolverActionPerformed

    private void jRechazarAmistadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRechazarAmistadActionPerformed
        String solicitudSeleccionada = jListaSolicitudes.getSelectedValue().toString();
        controlador.rechazarSolicitud(usuario, solicitudSeleccionada);
        init();
    }//GEN-LAST:event_jRechazarAmistadActionPerformed

    private void jAceptarAmistadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAceptarAmistadActionPerformed
        String solicitudSeleccionada = jListaSolicitudes.getSelectedValue().toString();
        controlador.aceptarSolicitud(usuario, solicitudSeleccionada, this);
        init();
    }//GEN-LAST:event_jAceptarAmistadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SolicitudAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SolicitudAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SolicitudAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SolicitudAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SolicitudAmistad(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAceptarAmistad;
    private javax.swing.JButton jBotonVolver;
    private javax.swing.JLabel jLabelSolicitudes;
    private javax.swing.JList jListaSolicitudes;
    private javax.swing.JButton jRechazarAmistad;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
